### ISSUE TITLE
Build fails after adding ethereum-dissectors to plugin list

### ISSUE THREAD

**Issue by timjp87** [ConsenSys/ethereum-dissectors#15]
I'm on macOS 10.13.6 building wireshark from commit dfc7fcc in my wireshare-ninja directory worked fine after also installing qt5 with homebrew. I then cloned the ethereum-dissectors repo and symlinked it into the plugins directory as described in the README. I modified the CMakeList.txt to append the new plugin directory to the list and cleaned my build directory.

After rebuilding the configuration with cmake and running the build with ninja it fails with:
https://gist.github.com/timjp87/66a53fe7c5a840993de341bc2b86b036

**Comment by gsalgado** [comment]
ISTM the plugin only works with wireshark 2.6. I had a similar error when I tried to build it against the latest HEAD of wireshark, but was able to build when using the `wireshark-2.6.2` tag

**Comment by timjp87** [comment]
Thank you for the solution. I propose updating the documentation.
#17 should prevent people from running into this problem.

**Comment by timjp87** [comment]
Closing because PR was merged.
